name: movie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7

  # DI
  get_it: ^8.0.2

  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0

  # Storage
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  cached_network_image: ^3.4.1

  # Network Utils
  connectivity_plus: ^7.0.0

  # UI
  flutter_screenutil: ^5.9.3
  go_router: ^16.3.0
  shimmer_animation: ^2.1.0+1

  # Env
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  retrofit_generator: ^10.0.6
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
